title: Yuchen Guo
logo: assets/img/room3.jpg
description:I am a Postdoctoral Fellow, CUHK-UC San Diego Joint Laboratory on Chinese Economy; Department of Economics, Chinese University of Hong Kong.
show_downloads: false
google_analytics:
theme: 
plugins:
  - jekyll-seo-tag
  # 删掉 jekyll-sitemap 这一行
